### PR TITLE
Add eslint config for standard to project

### PR DESCRIPTION
**Pull request by rtablada**
While the standard coding style should be enforced, there are a few big wins by using the eslint-config-standard over the command line `standard` package.

The largest win is tooling for auto fixing.
Eslint has support for autofixing similar to that of `standard-format` but I find most people will have eslint tooling.

So, this is a bit best of both worlds, you get the rules of standard, but the tooling of eslint for contributors.

### CODE REVIEW

**Comment by RomainLanz** [comment]
It should be also great to configure a hook to outrun the auto fixing before merging the PR. 👍

**Comment by thetutlage** [comment]
Travis runs the `lint` command, so it will take care of it automatically

**Comment by RomainLanz** [comment]
Yes, Travis will throw an error if rules aren't followed, but I mean why not create a `fix-link` command and run it before github merge the PR? In that way we don't need to be aware of "linting".

**Comment by rtablada** [comment]
@RomainLanz I'm not sure if github could do that reliably or at all. I know companies that have pre-push hooks, but git hooks only live in the local development and I think asking devs to have to setup hooks and set them up is too much of a hassle.

One thing to maybe look at (which would be a separate PR), would be setting up homu which if I understand it can do things like updating changelogs or contributing docs, squashing commits, and running lint fixes on merge.

**Comment by thetutlage** [comment]
@rtablada Looking at the **standard.js** `package.json` file, they include these dependencies in one of their newer releases https://github.com/feross/standard/blob/master/package.json#L16.

**Comment by rtablada** [comment]
Cool I'll check that out. We may get by with just the eslintrc then and bumping standard. I'll check it out now.

**Comment by thetutlage** [comment]
I have updated standard to the latest version. Closing this issue. Thanks 😄

**Comment by rtablada** [comment]
I will still pull squash and just add eslintrc

**Comment by thetutlage** [comment]
@rtablada  After going through http://standardjs.com, I see

> No decisions to make. No .eslintrc, .jshintrc, or .jscsrc files to manage. It just works.

So what value `.eslintrc` will add?

**Comment by rtablada** [comment]
> the tooling of eslint for contributors

Lots of potential contributors already have eslint linters installed in their editors. We can still use the standard config (and I'm gonna try to see if we can do it without extra installation) but just the simple process of adding the `.eslintrc` will allow those tools to streamline development.

**Pull request closed without merging**
